---
# tasks file for python-pip
- name: Check pip is installed anywhere but CentOS
  package:
    name: python-pip
    state: latest
  become: True
  become_method: "{{ become_method }}"
  when: ansible_os_family != "RedHat"

- name: Check pip is installed in CentOS
  shell: 'curl https://bootstrap.pypa.io/get-pip.py | python -'
  become: True
  become_method: "{{ become_method }}"
  when: ansible_os_family == "RedHat"
