---
# tasks file for python-pip
- name: Install epel only for CentOS in order to install pip
  yum:
    name=epel-release
    state=present
  become: True
  become_method: "{{ become_type }}"
  when: ansible_os_family == "RedHat"

- name: Install pip
  package:
    name: python-pip
    state: present
  become: True
  become_method: "{{ become_type }}"
